export enum Pages {
  HOME = '',
  AUTH = 'auth',
  SIGN_IN = `${Pages.AUTH}/signin`,
  SIGN_UP = `${Pages.AUTH}/signup`,
  DASHBOARD = 'dashboard',
  ABOUT = 'about',
  BIO = 'bio',
  SERVICES = 'services',
  ATENDIMENTO = 'atendimento',
  ATENDIMENTO_INDIVIDUAL = `${Pages.ATENDIMENTO}/individual`,
  ATENDIMENTO_GRUPO = `${Pages.ATENDIMENTO}/grupo`,
  ANALISE_REICHANA = `${Pages.ATENDIMENTO_INDIVIDUAL}/analise-reichana`,
  MINDFULLNESS = `${Pages.ATENDIMENTO_INDIVIDUAL}/mindfulness`,
  CONTACT = 'contact',
  SCHEDULING = 'scheduling',
  LUANE = `${Pages.BIO}/luane`,
  RAYSSA = `${Pages.BIO}/rayssa`,
  YARA = `${Pages.BIO}/yara`,
}
