import { CountryModel } from '../app/shared/models/country.model';

export const Countries: CountryModel[] = [
  {
    capital: 'Kabul',
    code: 'af',
    continent: 'Asia',
    iso: true,
    name: 'Afghanistan',
    ISOCode: '004',
    InternationalAreaCode: 93,
    LengthOfInternationalAreaCode: 4,
  },
  {
    capital: 'Cairo',
    code: 'eg',
    continent: 'Africa',
    iso: true,
    name: 'Egypt',
    ISOCode: '818',
    InternationalAreaCode: 20,
    LengthOfInternationalAreaCode: 4,
  },
  {
    capital: 'Tirana',
    code: 'al',
    continent: 'Europe',
    iso: true,
    name: 'Albania',
    ISOCode: '008',
    InternationalAreaCode: 355,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Algiers',
    code: 'dz',
    continent: 'Africa',
    iso: true,
    name: 'Algeria',
    ISOCode: '012',
    InternationalAreaCode: 213,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Pago Pago',
    code: 'as',
    continent: 'Oceania',
    iso: true,
    name: 'American Samoa',
    ISOCode: '016',
    InternationalAreaCode: 1684,
    LengthOfInternationalAreaCode: 6,
  },
  {
    capital: 'Andorra la Vella',
    code: 'ad',
    continent: 'Europe',
    iso: true,
    name: 'Andorra',
    ISOCode: '020',
    InternationalAreaCode: 376,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Luanda',
    code: 'ao',
    continent: 'Africa',
    iso: true,
    name: 'Angola',
    ISOCode: '024',
    InternationalAreaCode: 244,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'The Valley',
    code: 'ai',
    continent: 'North America',
    iso: true,
    name: 'Anguilla',
    ISOCode: '660',
    InternationalAreaCode: 1264,
    LengthOfInternationalAreaCode: 6,
  },
  {
    code: 'aq',
    iso: true,
    name: 'Antarctica',
    ISOCode: '010',
    InternationalAreaCode: 672,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: "St. John's",
    code: 'ag',
    continent: 'North America',
    iso: true,
    name: 'Antigua and Barbuda',
    ISOCode: '028',
    InternationalAreaCode: 1268,
    LengthOfInternationalAreaCode: 6,
  },
  {
    capital: 'Malabo',
    code: 'gq',
    continent: 'Africa',
    iso: true,
    name: 'Equatorial Guinea',
    ISOCode: '226',
    InternationalAreaCode: 240,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Buenos Aires',
    code: 'ar',
    continent: 'South America',
    iso: true,
    name: 'Argentina',
    ISOCode: '032',
    InternationalAreaCode: 54,
    LengthOfInternationalAreaCode: 4,
  },
  {
    capital: 'Yerevan',
    code: 'am',
    continent: 'Asia',
    iso: true,
    name: 'Armenia',
    ISOCode: '051',
    InternationalAreaCode: 374,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Oranjestad',
    code: 'aw',
    continent: 'South America',
    iso: true,
    name: 'Aruba',
    ISOCode: '533',
    InternationalAreaCode: 297,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Baku',
    code: 'az',
    continent: 'Asia',
    iso: true,
    name: 'Azerbaijan',
    ISOCode: '031',
    InternationalAreaCode: 994,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Addis Ababa',
    code: 'et',
    continent: 'Africa',
    iso: true,
    name: 'Ethiopia',
    ISOCode: '231',
    InternationalAreaCode: 251,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Canberra',
    code: 'au',
    continent: 'Oceania',
    iso: true,
    name: 'Australia',
    ISOCode: '036',
    InternationalAreaCode: 61,
    LengthOfInternationalAreaCode: 4,
  },
  {
    capital: 'Nassau',
    code: 'bs',
    continent: 'North America',
    iso: true,
    name: 'Bahamas',
    ISOCode: '044',
    InternationalAreaCode: 1242,
    LengthOfInternationalAreaCode: 6,
  },
  {
    capital: 'Manama',
    code: 'bh',
    continent: 'Asia',
    iso: true,
    name: 'Bahrain',
    ISOCode: '048',
    InternationalAreaCode: 973,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Dhaka',
    code: 'bd',
    continent: 'Asia',
    iso: true,
    name: 'Bangladesh',
    ISOCode: '050',
    InternationalAreaCode: 880,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Bridgetown',
    code: 'bb',
    continent: 'North America',
    iso: true,
    name: 'Barbados',
    ISOCode: '052',
    InternationalAreaCode: 1246,
    LengthOfInternationalAreaCode: 6,
  },
  {
    capital: 'Minsk',
    code: 'by',
    continent: 'Europe',
    iso: true,
    name: 'Belarus',
    ISOCode: '112',
    InternationalAreaCode: 375,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Brussels',
    code: 'be',
    continent: 'Europe',
    iso: true,
    name: 'Belgium',
    ISOCode: '056',
    InternationalAreaCode: 32,
    LengthOfInternationalAreaCode: 4,
  },
  {
    capital: 'Belmopan',
    code: 'bz',
    continent: 'North America',
    iso: true,
    name: 'Belize',
    ISOCode: '084',
    InternationalAreaCode: 501,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Porto-Novo',
    code: 'bj',
    continent: 'Africa',
    iso: true,
    name: 'Benin',
    ISOCode: '204',
    InternationalAreaCode: 229,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Hamilton',
    code: 'bm',
    continent: 'North America',
    iso: true,
    name: 'Bermuda',
    ISOCode: '060',
    InternationalAreaCode: 1441,
    LengthOfInternationalAreaCode: 6,
  },
  {
    capital: 'Thimphu',
    code: 'bt',
    continent: 'Asia',
    iso: true,
    name: 'Bhutan',
    ISOCode: '064',
    InternationalAreaCode: 975,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Sucre',
    code: 'bo',
    continent: 'South America',
    iso: true,
    name: 'Bolivia',
    ISOCode: '068',
    InternationalAreaCode: 591,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Sarajevo',
    code: 'ba',
    continent: 'Europe',
    iso: true,
    name: 'Bosnia and Herzegovina',
    ISOCode: '070',
    InternationalAreaCode: 387,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Gaborone',
    code: 'bw',
    continent: 'Africa',
    iso: true,
    name: 'Botswana',
    ISOCode: '072',
    InternationalAreaCode: 267,
    LengthOfInternationalAreaCode: 5,
  },
  {
    code: 'bv',
    iso: true,
    name: 'Bouvet Island',
    ISOCode: '074',
    InternationalAreaCode: 47,
    LengthOfInternationalAreaCode: 4,
  },
  {
    capital: 'Brasília',
    code: 'br',
    continent: 'South America',
    iso: true,
    name: 'Brazil',
    ISOCode: '076',
    InternationalAreaCode: 55,
    LengthOfInternationalAreaCode: 4,
  },
  {
    capital: 'Road Town',
    code: 'vg',
    continent: 'North America',
    iso: true,
    name: 'Virgin Islands (British)',
    ISOCode: '092',
    InternationalAreaCode: 1284,
    LengthOfInternationalAreaCode: 6,
  },
  {
    capital: 'Diego Garcia',
    code: 'io',
    continent: 'Asia',
    iso: true,
    name: 'British Indian Ocean Territory',
    ISOCode: '086',
    InternationalAreaCode: 246,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Bandar Seri Begawan',
    code: 'bn',
    continent: 'Asia',
    iso: true,
    name: 'Brunei Darussalam',
    ISOCode: '096',
    InternationalAreaCode: 673,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Sofia',
    code: 'bg',
    continent: 'Europe',
    iso: true,
    name: 'Bulgaria',
    ISOCode: '100',
    InternationalAreaCode: 359,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Ouagadougou',
    code: 'bf',
    continent: 'Africa',
    iso: true,
    name: 'Burkina Faso',
    ISOCode: '854',
    InternationalAreaCode: 226,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Bujumbura',
    code: 'bi',
    continent: 'Africa',
    iso: true,
    name: 'Burundi',
    ISOCode: '108',
    InternationalAreaCode: 257,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Santiago',
    code: 'cl',
    continent: 'South America',
    iso: true,
    name: 'Chile',
    ISOCode: '152',
    InternationalAreaCode: 56,
    LengthOfInternationalAreaCode: 4,
  },
  {
    capital: 'Beijing',
    code: 'cn',
    continent: 'Asia',
    iso: true,
    name: 'China',
    ISOCode: '156',
    InternationalAreaCode: 86,
    LengthOfInternationalAreaCode: 4,
  },
  {
    capital: 'Avarua',
    code: 'ck',
    continent: 'Oceania',
    iso: true,
    name: 'Cook Islands',
    ISOCode: '184',
    InternationalAreaCode: 682,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'San José',
    code: 'cr',
    continent: 'North America',
    iso: true,
    name: 'Costa Rica',
    ISOCode: '188',
    InternationalAreaCode: 506,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Yamoussoukro',
    code: 'ci',
    continent: 'Africa',
    iso: true,
    name: "Côte d'Ivoire",
    ISOCode: '384',
    InternationalAreaCode: 225,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Copenhagen',
    code: 'dk',
    continent: 'Europe',
    iso: true,
    name: 'Denmark',
    ISOCode: '208',
    InternationalAreaCode: 45,
    LengthOfInternationalAreaCode: 4,
  },
  {
    capital: 'Roseau',
    code: 'dm',
    continent: 'North America',
    iso: true,
    name: 'Dominica',
    ISOCode: '212',
    InternationalAreaCode: 1767,
    LengthOfInternationalAreaCode: 6,
  },
  {
    capital: 'Santo Domingo',
    code: 'do',
    continent: 'North America',
    iso: true,
    name: 'Dominican Republic',
    ISOCode: '214',
    InternationalAreaCode: 1809,
    LengthOfInternationalAreaCode: 6,
  },
  {
    capital: 'Djibouti',
    code: 'dj',
    continent: 'Africa',
    iso: true,
    name: 'Djibouti',
    ISOCode: '262',
    InternationalAreaCode: 253,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Quito',
    code: 'ec',
    continent: 'South America',
    iso: true,
    name: 'Ecuador',
    ISOCode: '218',
    InternationalAreaCode: 593,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'San Salvador',
    code: 'sv',
    continent: 'North America',
    iso: true,
    name: 'El Salvador',
    ISOCode: '222',
    InternationalAreaCode: 503,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Asmara',
    code: 'er',
    continent: 'Africa',
    iso: true,
    name: 'Eritrea',
    ISOCode: '232',
    InternationalAreaCode: 291,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Tallinn',
    code: 'ee',
    continent: 'Europe',
    iso: true,
    name: 'Estonia',
    ISOCode: '233',
    InternationalAreaCode: 372,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Stanley',
    code: 'fk',
    continent: 'South America',
    iso: true,
    name: 'Falkland Islands',
    ISOCode: '238',
    InternationalAreaCode: 500,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Tórshavn',
    code: 'fo',
    continent: 'Europe',
    iso: true,
    name: 'Faroe Islands',
    ISOCode: '234',
    InternationalAreaCode: 298,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Suva',
    code: 'fj',
    continent: 'Oceania',
    iso: true,
    name: 'Fiji',
    ISOCode: '242',
    InternationalAreaCode: 679,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Helsinki',
    code: 'fi',
    continent: 'Europe',
    iso: true,
    name: 'Finland',
    ISOCode: '246',
    InternationalAreaCode: 358,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Paris',
    code: 'fr',
    continent: 'Europe',
    iso: true,
    name: 'France',
    ISOCode: '250',
    InternationalAreaCode: 33,
    LengthOfInternationalAreaCode: 4,
  },
  {
    capital: 'Papeete',
    code: 'pf',
    continent: 'Oceania',
    iso: true,
    name: 'French Polynesia',
    ISOCode: '258',
    InternationalAreaCode: 689,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Saint Pierre',
    code: 'tf',
    continent: 'Antarctica',
    iso: true,
    name: 'French Southern and Antarctic Lands',
    ISOCode: '260',
    InternationalAreaCode: 262,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Libreville',
    code: 'ga',
    continent: 'Africa',
    iso: true,
    name: 'Gabon',
    ISOCode: '266',
    InternationalAreaCode: 241,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Banjul',
    code: 'gm',
    continent: 'Africa',
    iso: true,
    name: 'Gambia',
    ISOCode: '270',
    InternationalAreaCode: 220,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Tbilisi',
    code: 'ge',
    continent: 'Asia',
    iso: true,
    name: 'Georgia',
    ISOCode: '268',
    InternationalAreaCode: 995,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Berlin',
    code: 'de',
    continent: 'Europe',
    iso: true,
    name: 'Germany',
    ISOCode: '276',
    InternationalAreaCode: 49,
    LengthOfInternationalAreaCode: 4,
  },
  {
    capital: 'Accra',
    code: 'gh',
    continent: 'Africa',
    iso: true,
    name: 'Ghana',
    ISOCode: '288',
    InternationalAreaCode: 233,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Gibraltar',
    code: 'gi',
    continent: 'Europe',
    iso: true,
    name: 'Gibraltar',
    ISOCode: '292',
    InternationalAreaCode: 350,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: "St. George's",
    code: 'gd',
    continent: 'North America',
    iso: true,
    name: 'Grenada',
    ISOCode: '308',
    InternationalAreaCode: 1473,
    LengthOfInternationalAreaCode: 6,
  },
  {
    capital: 'Athens',
    code: 'gr',
    continent: 'Europe',
    iso: true,
    name: 'Greece',
    ISOCode: '300',
    InternationalAreaCode: 30,
    LengthOfInternationalAreaCode: 4,
  },
  {
    capital: 'Nuuk',
    code: 'gl',
    continent: 'North America',
    iso: true,
    name: 'Greenland',
    ISOCode: '304',
    InternationalAreaCode: 299,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Hagåtña',
    code: 'gu',
    continent: 'Oceania',
    iso: true,
    name: 'Guam',
    ISOCode: '316',
    InternationalAreaCode: 1671,
    LengthOfInternationalAreaCode: 6,
  },
  {
    capital: 'Guatemala City',
    code: 'gt',
    continent: 'North America',
    iso: true,
    name: 'Guatemala',
    ISOCode: '320',
    InternationalAreaCode: 502,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Saint Peter Port',
    code: 'gg',
    continent: 'Europe',
    iso: true,
    name: 'Guernsey',
    ISOCode: '831',
    InternationalAreaCode: 441481,
    LengthOfInternationalAreaCode: 8,
  },
  {
    capital: 'Conakry',
    code: 'gn',
    continent: 'Africa',
    iso: true,
    name: 'Guinea',
    ISOCode: '324',
    InternationalAreaCode: 224,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Bissau',
    code: 'gw',
    continent: 'Africa',
    iso: true,
    name: 'Guinea-Bissau',
    ISOCode: '624',
    InternationalAreaCode: 245,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Georgetown',
    code: 'gy',
    continent: 'South America',
    iso: true,
    name: 'Guyana',
    ISOCode: '328',
    InternationalAreaCode: 592,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Port-au-Prince',
    code: 'ht',
    continent: 'North America',
    iso: true,
    name: 'Haiti',
    ISOCode: '332',
    InternationalAreaCode: 509,
    LengthOfInternationalAreaCode: 5,
  },
  {
    code: 'hm',
    iso: true,
    name: 'Heard Island and McDonald Islands',
    ISOCode: '334',
    InternationalAreaCode: 672,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Tegucigalpa',
    code: 'hn',
    continent: 'North America',
    iso: true,
    name: 'Honduras',
    ISOCode: '340',
    InternationalAreaCode: 504,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'New Delhi',
    code: 'in',
    continent: 'Asia',
    iso: true,
    name: 'India',
    ISOCode: '356',
    InternationalAreaCode: 91,
    LengthOfInternationalAreaCode: 4,
  },
  {
    capital: 'Jakarta',
    code: 'id',
    continent: 'Asia',
    iso: true,
    name: 'Indonesia',
    ISOCode: '360',
    InternationalAreaCode: 62,
    LengthOfInternationalAreaCode: 4,
  },
  {
    capital: 'Douglas',
    code: 'im',
    continent: 'Europe',
    iso: true,
    name: 'Isle of Man',
    ISOCode: '833',
    InternationalAreaCode: 441624,
    LengthOfInternationalAreaCode: 8,
  },
  {
    capital: 'Baghdad',
    code: 'iq',
    continent: 'Asia',
    iso: true,
    name: 'Iraq',
    ISOCode: '368',
    InternationalAreaCode: 964,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Tehran',
    code: 'ir',
    continent: 'Asia',
    iso: true,
    name: 'Iran',
    ISOCode: '364',
    InternationalAreaCode: 98,
    LengthOfInternationalAreaCode: 4,
  },
  {
    capital: 'Dublin',
    code: 'ie',
    continent: 'Europe',
    iso: true,
    name: 'Ireland',
    ISOCode: '372',
    InternationalAreaCode: 353,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Reykjavik',
    code: 'is',
    continent: 'Europe',
    iso: true,
    name: 'Iceland',
    ISOCode: '352',
    InternationalAreaCode: 354,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Jerusalem',
    code: 'il',
    continent: 'Asia',
    iso: true,
    name: 'Israel',
    ISOCode: '376',
    InternationalAreaCode: 972,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Rome',
    code: 'it',
    continent: 'Europe',
    iso: true,
    name: 'Italy',
    ISOCode: '380',
    InternationalAreaCode: 39,
    LengthOfInternationalAreaCode: 4,
  },
  {
    capital: 'Kingston',
    code: 'jm',
    continent: 'North America',
    iso: true,
    name: 'Jamaica',
    ISOCode: '388',
    InternationalAreaCode: 1876,
    LengthOfInternationalAreaCode: 6,
  },
  {
    capital: 'Tokyo',
    code: 'jp',
    continent: 'Asia',
    iso: true,
    name: 'Japan',
    ISOCode: '392',
    InternationalAreaCode: 81,
    LengthOfInternationalAreaCode: 4,
  },
  {
    capital: "Sana'a",
    code: 'ye',
    continent: 'Asia',
    iso: true,
    name: 'Yemen',
    ISOCode: '887',
    InternationalAreaCode: 967,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Saint Helier',
    code: 'je',
    continent: 'Europe',
    iso: true,
    name: 'Jersey',
    ISOCode: '832',
    InternationalAreaCode: 441534,
    LengthOfInternationalAreaCode: 8,
  },
  {
    capital: 'Amman',
    code: 'jo',
    continent: 'Asia',
    iso: true,
    name: 'Jordan',
    ISOCode: '400',
    InternationalAreaCode: 962,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'George Town',
    code: 'ky',
    continent: 'North America',
    iso: true,
    name: 'Cayman Islands',
    ISOCode: '136',
    InternationalAreaCode: 1345,
    LengthOfInternationalAreaCode: 6,
  },
  {
    capital: 'Phnom Penh',
    code: 'kh',
    continent: 'Asia',
    iso: true,
    name: 'Cambodia',
    ISOCode: '116',
    InternationalAreaCode: 855,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Yaoundé',
    code: 'cm',
    continent: 'Africa',
    iso: true,
    name: 'Cameroon',
    ISOCode: '120',
    InternationalAreaCode: 237,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Ottawa',
    code: 'ca',
    continent: 'North America',
    iso: true,
    name: 'Canada',
    ISOCode: '124',
    InternationalAreaCode: 1,
    LengthOfInternationalAreaCode: 3,
  },
  {
    capital: 'Praia',
    code: 'cv',
    continent: 'Africa',
    iso: true,
    name: 'Cabo Verde',
    ISOCode: '132',
    InternationalAreaCode: 238,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Astana',
    code: 'kz',
    continent: 'Asia',
    iso: true,
    name: 'Kazakhstan',
    ISOCode: '398',
    InternationalAreaCode: 7,
    LengthOfInternationalAreaCode: 3,
  },
  {
    capital: 'Doha',
    code: 'qa',
    continent: 'Asia',
    iso: true,
    name: 'Qatar',
    ISOCode: '634',
    InternationalAreaCode: 974,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Nairobi',
    code: 'ke',
    continent: 'Africa',
    iso: true,
    name: 'Kenya',
    ISOCode: '404',
    InternationalAreaCode: 254,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Bishkek',
    code: 'kg',
    continent: 'Asia',
    iso: true,
    name: 'Kyrgyzstan',
    ISOCode: '417',
    InternationalAreaCode: 996,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'South Tarawa',
    code: 'ki',
    continent: 'Oceania',
    iso: true,
    name: 'Kiribati',
    ISOCode: '296',
    InternationalAreaCode: 686,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'West Island',
    code: 'cc',
    continent: 'Asia',
    iso: true,
    name: 'Cocos (Keeling) Islands',
    ISOCode: '166',
    InternationalAreaCode: 61,
    LengthOfInternationalAreaCode: 4,
  },
  {
    capital: 'Bogotá',
    code: 'co',
    continent: 'South America',
    iso: true,
    name: 'Colombia',
    ISOCode: '170',
    InternationalAreaCode: 57,
    LengthOfInternationalAreaCode: 4,
  },
  {
    capital: 'Brazzaville',
    code: 'cg',
    continent: 'Africa',
    iso: true,
    name: 'Republic of the Congo',
    ISOCode: '178',
    InternationalAreaCode: 242,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Kinshasa',
    code: 'cd',
    continent: 'Africa',
    iso: true,
    name: 'Democratic Republic of the Congo',
    ISOCode: '180',
    InternationalAreaCode: 243,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Pristina',
    code: 'xk',
    continent: 'Europe',
    iso: false,
    name: 'Kosovo',
    ISOCode: '900',
    InternationalAreaCode: 383,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Zagreb',
    code: 'hr',
    continent: 'Europe',
    iso: true,
    name: 'Croatia',
    ISOCode: '191',
    InternationalAreaCode: 385,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Havana',
    code: 'cu',
    continent: 'North America',
    iso: true,
    name: 'Cuba',
    ISOCode: '192',
    InternationalAreaCode: 53,
    LengthOfInternationalAreaCode: 4,
  },
  {
    capital: 'Kuwait City',
    code: 'kw',
    continent: 'Asia',
    iso: true,
    name: 'Kuwait',
    ISOCode: '414',
    InternationalAreaCode: 965,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Vientiane',
    code: 'la',
    continent: 'Asia',
    iso: true,
    name: 'Laos',
    ISOCode: '418',
    InternationalAreaCode: 856,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Maseru',
    code: 'ls',
    continent: 'Africa',
    iso: true,
    name: 'Lesotho',
    ISOCode: '426',
    InternationalAreaCode: 266,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Riga',
    code: 'lv',
    continent: 'Europe',
    iso: true,
    name: 'Latvia',
    ISOCode: '428',
    InternationalAreaCode: 371,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Beirut',
    code: 'lb',
    continent: 'Asia',
    iso: true,
    name: 'Lebanon',
    ISOCode: '422',
    InternationalAreaCode: 961,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Monrovia',
    code: 'lr',
    continent: 'Africa',
    iso: true,
    name: 'Liberia',
    ISOCode: '430',
    InternationalAreaCode: 231,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Tripoli',
    code: 'ly',
    continent: 'Africa',
    iso: true,
    name: 'Libya',
    ISOCode: '434',
    InternationalAreaCode: 218,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Vaduz',
    code: 'li',
    continent: 'Europe',
    iso: true,
    name: 'Liechtenstein',
    ISOCode: '438',
    InternationalAreaCode: 423,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Vilnius',
    code: 'lt',
    continent: 'Europe',
    iso: true,
    name: 'Lithuania',
    ISOCode: '440',
    InternationalAreaCode: 370,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Luxembourg City',
    code: 'lu',
    continent: 'Europe',
    iso: true,
    name: 'Luxembourg',
    ISOCode: '442',
    InternationalAreaCode: 352,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Macau',
    code: 'mo',
    continent: 'Asia',
    iso: true,
    name: 'Macau',
    ISOCode: '446',
    InternationalAreaCode: 853,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Antananarivo',
    code: 'mg',
    continent: 'Africa',
    iso: true,
    name: 'Madagascar',
    ISOCode: '450',
    InternationalAreaCode: 261,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Lilongwe',
    code: 'mw',
    continent: 'Africa',
    iso: true,
    name: 'Malawi',
    ISOCode: '454',
    InternationalAreaCode: 265,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Kuala Lumpur',
    code: 'my',
    continent: 'Asia',
    iso: true,
    name: 'Malaysia',
    ISOCode: '458',
    InternationalAreaCode: 60,
    LengthOfInternationalAreaCode: 4,
  },
  {
    capital: 'Malé',
    code: 'mv',
    continent: 'Asia',
    iso: true,
    name: 'Maldives',
    ISOCode: '462',
    InternationalAreaCode: 960,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Bamako',
    code: 'ml',
    continent: 'Africa',
    iso: true,
    name: 'Mali',
    ISOCode: '466',
    InternationalAreaCode: 223,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Valletta',
    code: 'mt',
    continent: 'Europe',
    iso: true,
    name: 'Malta',
    ISOCode: '470',
    InternationalAreaCode: 356,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Rabat',
    code: 'ma',
    continent: 'Africa',
    iso: true,
    name: 'Morocco',
    ISOCode: '504',
    InternationalAreaCode: 212,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Majuro',
    code: 'mh',
    continent: 'Oceania',
    iso: true,
    name: 'Marshall Islands',
    ISOCode: '584',
    InternationalAreaCode: 692,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Fort-de-France',
    code: 'mq',
    continent: 'North America',
    iso: true,
    name: 'Martinique',
    ISOCode: '474',
    InternationalAreaCode: 596,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Nouakchott',
    code: 'mr',
    continent: 'Africa',
    iso: true,
    name: 'Mauritania',
    ISOCode: '478',
    InternationalAreaCode: 222,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Port Louis',
    code: 'mu',
    continent: 'Africa',
    iso: true,
    name: 'Mauritius',
    ISOCode: '480',
    InternationalAreaCode: 230,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Mamoudzou',
    code: 'yt',
    continent: 'Africa',
    iso: true,
    name: 'Mayotte',
    ISOCode: '175',
    InternationalAreaCode: 262,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Mexico City',
    code: 'mx',
    continent: 'North America',
    iso: true,
    name: 'Mexico',
    ISOCode: '484',
    InternationalAreaCode: 52,
    LengthOfInternationalAreaCode: 4,
  },
  {
    capital: 'Palikir',
    code: 'fm',
    continent: 'Oceania',
    iso: true,
    name: 'Federated States of Micronesia',
    ISOCode: '583',
    InternationalAreaCode: 691,
    LengthOfInternationalAreaCode: 5,
  },

  {
    capital: 'Chișinău',
    code: 'md',
    continent: 'Europe',
    iso: true,
    name: 'Moldova',
    ISOCode: '498',
    InternationalAreaCode: 373,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Ulaanbaatar',
    code: 'mn',
    continent: 'Asia',
    iso: true,
    name: 'Mongolia',
    ISOCode: '496',
    InternationalAreaCode: 976,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Podgorica',
    code: 'me',
    continent: 'Europe',
    iso: true,
    name: 'Montenegro',
    ISOCode: '499',
    InternationalAreaCode: 382,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Little Bay, Brades, Plymouth',
    code: 'ms',
    continent: 'North America',
    iso: true,
    name: 'Montserrat',
    ISOCode: '500',
    InternationalAreaCode: 1664,
    LengthOfInternationalAreaCode: 6,
  },

  {
    capital: 'Maputo',
    code: 'mz',
    continent: 'Africa',
    iso: true,
    name: 'Mozambique',
    ISOCode: '508',
    InternationalAreaCode: 258,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Naypyidaw',
    code: 'mm',
    continent: 'Asia',
    iso: true,
    name: 'Myanmar',
    ISOCode: '104',
    InternationalAreaCode: 95,
    LengthOfInternationalAreaCode: 4,
  },
  {
    capital: 'Windhoek',
    code: 'na',
    continent: 'Africa',
    iso: true,
    name: 'Namibia',
    ISOCode: '516',
    InternationalAreaCode: 264,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Yaren District',
    code: 'nr',
    continent: 'Oceania',
    iso: true,
    name: 'Nauru',
    ISOCode: '520',
    InternationalAreaCode: 674,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Kathmandu',
    code: 'np',
    continent: 'Asia',
    iso: true,
    name: 'Nepal',
    ISOCode: '524',
    InternationalAreaCode: 977,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Nouméa',
    code: 'nc',
    continent: 'Oceania',
    iso: true,
    name: 'New Caledonia',
    ISOCode: '540',
    InternationalAreaCode: 687,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Wellington',
    code: 'nz',
    continent: 'Oceania',
    iso: true,
    name: 'New Zealand',
    ISOCode: '554',
    InternationalAreaCode: 64,
    LengthOfInternationalAreaCode: 4,
  },
  {
    capital: 'Managua',
    code: 'ni',
    continent: 'North America',
    iso: true,
    name: 'Nicaragua',
    ISOCode: '558',
    InternationalAreaCode: 505,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Amsterdam',
    code: 'nl',
    continent: 'Europe',
    iso: true,
    name: 'Netherlands',
    ISOCode: '528',
    InternationalAreaCode: 31,
    LengthOfInternationalAreaCode: 4,
  },
  {
    capital: 'Niamey',
    code: 'ne',
    continent: 'Africa',
    iso: true,
    name: 'Niger',
    ISOCode: '562',
    InternationalAreaCode: 227,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Abuja',
    code: 'ng',
    continent: 'Africa',
    iso: true,
    name: 'Nigeria',
    ISOCode: '566',
    InternationalAreaCode: 234,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Alofi',
    code: 'nu',
    continent: 'Oceania',
    iso: true,
    name: 'Niue',
    ISOCode: '570',
    InternationalAreaCode: 683,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Pyongyang',
    code: 'kp',
    continent: 'Asia',
    iso: true,
    name: 'North Korea',
    ISOCode: '408',
    InternationalAreaCode: 850,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Saipan',
    code: 'mp',
    continent: 'Oceania',
    iso: true,
    name: 'Northern Mariana Islands',
    ISOCode: '580',
    InternationalAreaCode: 1670,
    LengthOfInternationalAreaCode: 6,
  },
  {
    capital: 'Skopje',
    code: 'mk',
    continent: 'Europe',
    iso: true,
    name: 'North Macedonia',
    ISOCode: '807',
    InternationalAreaCode: 389,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Kingston',
    code: 'nf',
    continent: 'Oceania',
    iso: true,
    name: 'Norfolk Island',
    ISOCode: '574',
    InternationalAreaCode: 672,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Oslo',
    code: 'no',
    continent: 'Europe',
    iso: true,
    name: 'Norway',
    ISOCode: '578',
    InternationalAreaCode: 47,
    LengthOfInternationalAreaCode: 4,
  },
  {
    capital: 'Muscat',
    code: 'om',
    continent: 'Asia',
    iso: true,
    name: 'Oman',
    ISOCode: '512',
    InternationalAreaCode: 968,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Vienna',
    code: 'at',
    continent: 'Europe',
    iso: true,
    name: 'Austria',
    ISOCode: '040',
    InternationalAreaCode: 43,
    LengthOfInternationalAreaCode: 4,
  },
  {
    capital: 'Dili',
    code: 'tl',
    continent: 'Asia',
    iso: true,
    name: 'Timor-Leste',
    ISOCode: '626',
    InternationalAreaCode: 670,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Islamabad',
    code: 'pk',
    continent: 'Asia',
    iso: true,
    name: 'Pakistan',
    ISOCode: '586',
    InternationalAreaCode: 92,
    LengthOfInternationalAreaCode: 4,
  },
  {
    capital: 'Ngerulmud',
    code: 'pw',
    continent: 'Oceania',
    iso: true,
    name: 'Palau',
    ISOCode: '585',
    InternationalAreaCode: 680,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Panama City',
    code: 'pa',
    continent: 'North America',
    iso: true,
    name: 'Panama',
    ISOCode: '591',
    InternationalAreaCode: 507,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Port Moresby',
    code: 'pg',
    continent: 'Oceania',
    iso: true,
    name: 'Papua New Guinea',
    ISOCode: '598',
    InternationalAreaCode: 675,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Asunción',
    code: 'py',
    continent: 'South America',
    iso: true,
    name: 'Paraguay',
    ISOCode: '600',
    InternationalAreaCode: 595,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Lima',
    code: 'pe',
    continent: 'South America',
    iso: true,
    name: 'Peru',
    ISOCode: '604',
    InternationalAreaCode: 51,
    LengthOfInternationalAreaCode: 4,
  },
  {
    capital: 'Manila',
    code: 'ph',
    continent: 'Asia',
    iso: true,
    name: 'Philippines',
    ISOCode: '608',
    InternationalAreaCode: 63,
    LengthOfInternationalAreaCode: 4,
  },
  {
    capital: 'Adamstown',
    code: 'pn',
    continent: 'Oceania',
    iso: true,
    name: 'Pitcairn',
    ISOCode: '612',
    InternationalAreaCode: 64,
    LengthOfInternationalAreaCode: 4,
  },
  {
    capital: 'Warsaw',
    code: 'pl',
    continent: 'Europe',
    iso: true,
    name: 'Poland',
    ISOCode: '616',
    InternationalAreaCode: 48,
    LengthOfInternationalAreaCode: 4,
  },
  {
    capital: 'Lisbon',
    code: 'pt',
    continent: 'Europe',
    iso: true,
    name: 'Portugal',
    ISOCode: '620',
    InternationalAreaCode: 351,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'San Juan',
    code: 'pr',
    continent: 'North America',
    iso: true,
    name: 'Puerto Rico',
    ISOCode: '630',
    InternationalAreaCode: 1787,
    LengthOfInternationalAreaCode: 6,
  },
  {
    capital: 'Kigali',
    code: 'rw',
    continent: 'Africa',
    iso: true,
    name: 'Rwanda',
    ISOCode: '646',
    InternationalAreaCode: 250,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Bucharest',
    code: 'ro',
    continent: 'Europe',
    iso: true,
    name: 'Romania',
    ISOCode: '642',
    InternationalAreaCode: 40,
    LengthOfInternationalAreaCode: 4,
  },
  {
    capital: 'Moscow',
    code: 'ru',
    continent: 'Europe',
    iso: true,
    name: 'Russia',
    ISOCode: '643',
    InternationalAreaCode: 7,
    LengthOfInternationalAreaCode: 3,
  },
  {
    capital: 'Lusaka',
    code: 'zm',
    continent: 'Africa',
    iso: true,
    name: 'Zambia',
    ISOCode: '894',
    InternationalAreaCode: 260,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Apia',
    code: 'ws',
    continent: 'Oceania',
    iso: true,
    name: 'Samoa',
    ISOCode: '882',
    InternationalAreaCode: 685,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'San Marino',
    code: 'sm',
    continent: 'Europe',
    iso: true,
    name: 'San Marino',
    ISOCode: '674',
    InternationalAreaCode: 378,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'São Tomé',
    code: 'st',
    continent: 'Africa',
    iso: true,
    name: 'Sao Tome and Principe',
    ISOCode: '678',
    InternationalAreaCode: 239,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Riyadh',
    code: 'sa',
    continent: 'Asia',
    iso: true,
    name: 'Saudi Arabia',
    ISOCode: '682',
    InternationalAreaCode: 966,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Stockholm',
    code: 'se',
    continent: 'Europe',
    iso: true,
    name: 'Sweden',
    ISOCode: '752',
    InternationalAreaCode: 46,
    LengthOfInternationalAreaCode: 4,
  },
  {
    capital: 'Bern',
    code: 'ch',
    continent: 'Europe',
    iso: true,
    name: 'Switzerland',
    ISOCode: '756',
    InternationalAreaCode: 41,
    LengthOfInternationalAreaCode: 4,
  },
  {
    capital: 'Dakar',
    code: 'sn',
    continent: 'Africa',
    iso: true,
    name: 'Senegal',
    ISOCode: '686',
    InternationalAreaCode: 221,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Belgrade',
    code: 'rs',
    continent: 'Europe',
    iso: true,
    name: 'Serbia',
    ISOCode: '688',
    InternationalAreaCode: 381,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Victoria',
    code: 'sc',
    continent: 'Africa',
    iso: true,
    name: 'Seychelles',
    ISOCode: '690',
    InternationalAreaCode: 248,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Freetown',
    code: 'sl',
    continent: 'Africa',
    iso: true,
    name: 'Sierra Leone',
    ISOCode: '694',
    InternationalAreaCode: 232,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Harare',
    code: 'zw',
    continent: 'Africa',
    iso: true,
    name: 'Zimbabwe',
    ISOCode: '716',
    InternationalAreaCode: 263,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Singapore',
    code: 'sg',
    continent: 'Asia',
    iso: true,
    name: 'Singapore',
    ISOCode: '702',
    InternationalAreaCode: 65,
    LengthOfInternationalAreaCode: 4,
  },

  {
    capital: 'Bratislava',
    code: 'sk',
    continent: 'Europe',
    iso: true,
    name: 'Slovakia',
    ISOCode: '703',
    InternationalAreaCode: 421,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Ljubljana',
    code: 'si',
    continent: 'Europe',
    iso: true,
    name: 'Slovenia',
    ISOCode: '705',
    InternationalAreaCode: 386,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Mogadishu',
    code: 'so',
    continent: 'Africa',
    iso: true,
    name: 'Somalia',
    ISOCode: '706',
    InternationalAreaCode: 252,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Madrid',
    code: 'es',
    continent: 'Europe',
    iso: true,
    name: 'Spain',
    ISOCode: '724',
    InternationalAreaCode: 34,
    LengthOfInternationalAreaCode: 4,
  },
  {
    capital: 'Sri Jayawardenepura Kotte, Colombo',
    code: 'lk',
    continent: 'Asia',
    iso: true,
    name: 'Sri Lanka',
    ISOCode: '144',
    InternationalAreaCode: 94,
    LengthOfInternationalAreaCode: 4,
  },
  {
    capital: 'Jamestown',
    code: 'sh',
    continent: 'Africa',
    iso: true,
    name: 'Saint Helena, Ascension and Tristan da Cunha',
    ISOCode: '654',
    InternationalAreaCode: 290,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Basseterre',
    code: 'kn',
    continent: 'North America',
    iso: true,
    name: 'Saint Kitts and Nevis',
    ISOCode: '659',
    InternationalAreaCode: 1869,
    LengthOfInternationalAreaCode: 6,
  },
  {
    capital: 'Castries',
    code: 'lc',
    continent: 'North America',
    iso: true,
    name: 'Saint Lucia',
    ISOCode: '662',
    InternationalAreaCode: 1758,
    LengthOfInternationalAreaCode: 6,
  },
  {
    capital: 'Saint-Pierre',
    code: 'pm',
    continent: 'North America',
    iso: true,
    name: 'Saint Pierre and Miquelon',
    ISOCode: '666',
    InternationalAreaCode: 508,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Kingstown',
    code: 'vc',
    continent: 'North America',
    iso: true,
    name: 'Saint Vincent and the Grenadines',
    ISOCode: '670',
    InternationalAreaCode: 1784,
    LengthOfInternationalAreaCode: 6,
  },
  {
    capital: 'Ramallah',
    code: 'ps',
    continent: 'Asia',
    iso: true,
    name: 'State of Palestine',
    ISOCode: '275',
    InternationalAreaCode: 970,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Pretoria',
    code: 'za',
    continent: 'Africa',
    iso: true,
    name: 'South Africa',
    ISOCode: '710',
    InternationalAreaCode: 27,
    LengthOfInternationalAreaCode: 4,
  },
  {
    capital: 'Khartoum',
    code: 'sd',
    continent: 'Africa',
    iso: true,
    name: 'Sudan',
    ISOCode: '729',
    InternationalAreaCode: 249,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'King Edward Point',
    code: 'gs',
    continent: 'Antarctica',
    iso: true,
    name: 'South Georgia and the South Sandwich Islands',
    ISOCode: '239',
    InternationalAreaCode: 500,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Seoul',
    code: 'kr',
    continent: 'Asia',
    iso: true,
    name: 'South Korea',
    ISOCode: '410',
    InternationalAreaCode: 82,
    LengthOfInternationalAreaCode: 4,
  },
  {
    capital: 'Paramaribo',
    code: 'sr',
    continent: 'South America',
    iso: true,
    name: 'Suriname',
    ISOCode: '740',
    InternationalAreaCode: 597,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Lobamba, Mbabane',
    code: 'sz',
    continent: 'Africa',
    iso: true,
    name: 'Eswatini',
    ISOCode: '748',
    InternationalAreaCode: 268,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Damascus',
    code: 'sy',
    continent: 'Asia',
    iso: true,
    name: 'Syria',
    ISOCode: '760',
    InternationalAreaCode: 963,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Dushanbe',
    code: 'tj',
    continent: 'Asia',
    iso: true,
    name: 'Tajikistan',
    ISOCode: '762',
    InternationalAreaCode: 992,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Taipei',
    code: 'tw',
    continent: 'Asia',
    iso: true,
    name: 'Taiwan',
    ISOCode: '158',
    InternationalAreaCode: 886,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Dodoma',
    code: 'tz',
    continent: 'Africa',
    iso: true,
    name: 'Tanzania',
    ISOCode: '834',
    InternationalAreaCode: 255,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Bangkok',
    code: 'th',
    continent: 'Asia',
    iso: true,
    name: 'Thailand',
    ISOCode: '764',
    InternationalAreaCode: 66,
    LengthOfInternationalAreaCode: 4,
  },
  {
    capital: 'Lomé',
    code: 'tg',
    continent: 'Africa',
    iso: true,
    name: 'Togo',
    ISOCode: '768',
    InternationalAreaCode: 228,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Nukunonu, Atafu,Tokelau',
    code: 'tk',
    continent: 'Oceania',
    iso: true,
    name: 'Tokelau',
    ISOCode: '772',
    InternationalAreaCode: 690,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Nukuʻalofa',
    code: 'to',
    continent: 'Oceania',
    iso: true,
    name: 'Tonga',
    ISOCode: '776',
    InternationalAreaCode: 676,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Port of Spain',
    code: 'tt',
    continent: 'South America',
    iso: true,
    name: 'Trinidad and Tobago',
    ISOCode: '780',
    InternationalAreaCode: 1868,
    LengthOfInternationalAreaCode: 6,
  },
  {
    capital: "N'Djamena",
    code: 'td',
    continent: 'Africa',
    iso: true,
    name: 'Chad',
    ISOCode: '148',
    InternationalAreaCode: 235,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Prague',
    code: 'cz',
    continent: 'Europe',
    iso: true,
    name: 'Czech Republic',
    ISOCode: '203',
    InternationalAreaCode: 420,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Tunis',
    code: 'tn',
    continent: 'Africa',
    iso: true,
    name: 'Tunisia',
    ISOCode: '788',
    InternationalAreaCode: 216,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Ashgabat',
    code: 'tm',
    continent: 'Asia',
    iso: true,
    name: 'Turkmenistan',
    ISOCode: '795',
    InternationalAreaCode: 993,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Cockburn Town',
    code: 'tc',
    continent: 'North America',
    iso: true,
    name: 'Turks and Caicos Islands',
    ISOCode: '796',
    InternationalAreaCode: 1649,
    LengthOfInternationalAreaCode: 6,
  },
  {
    capital: 'Funafuti',
    code: 'tv',
    continent: 'Oceania',
    iso: true,
    name: 'Tuvalu',
    ISOCode: '798',
    InternationalAreaCode: 688,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Ankara',
    code: 'tr',
    continent: 'Asia',
    iso: true,
    name: 'Türkiye',
    ISOCode: '792',
    InternationalAreaCode: 90,
    LengthOfInternationalAreaCode: 4,
  },
  {
    capital: 'Kampala',
    code: 'ug',
    continent: 'Africa',
    iso: true,
    name: 'Uganda',
    ISOCode: '800',
    InternationalAreaCode: 256,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Kiev',
    code: 'ua',
    continent: 'Europe',
    iso: true,
    name: 'Ukraine',
    ISOCode: '804',
    InternationalAreaCode: 380,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Budapest',
    code: 'hu',
    continent: 'Europe',
    iso: true,
    name: 'Hungary',
    ISOCode: '348',
    InternationalAreaCode: 36,
    LengthOfInternationalAreaCode: 4,
  },
  {
    capital: 'Montevideo',
    code: 'uy',
    continent: 'South America',
    iso: true,
    name: 'Uruguay',
    ISOCode: '858',
    InternationalAreaCode: 598,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Tashkent',
    code: 'uz',
    continent: 'Asia',
    iso: true,
    name: 'Uzbekistan',
    ISOCode: '860',
    InternationalAreaCode: 998,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Port Vila',
    code: 'vu',
    continent: 'Oceania',
    iso: true,
    name: 'Vanuatu',
    ISOCode: '548',
    InternationalAreaCode: 678,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Vatican City',
    code: 'va',
    continent: 'Europe',
    iso: true,
    name: 'Holy See',
    ISOCode: '336',
    InternationalAreaCode: 379,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Caracas',
    code: 've',
    continent: 'South America',
    iso: true,
    name: 'Venezuela',
    ISOCode: '862',
    InternationalAreaCode: 58,
    LengthOfInternationalAreaCode: 4,
  },
  {
    capital: 'Abu Dhabi',
    code: 'ae',
    continent: 'Asia',
    iso: true,
    name: 'United Arab Emirates',
    ISOCode: '784',
    InternationalAreaCode: 971,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Washington, D.C.',
    code: 'us',
    continent: 'North America',
    iso: true,
    name: 'United States of America',
    ISOCode: '840',
    InternationalAreaCode: 1,
    LengthOfInternationalAreaCode: 3,
  },
  {
    capital: 'London',
    code: 'gb-eng',
    continent: 'Europe',
    iso: false,
    name: 'England',
    ISOCode: '826',
    InternationalAreaCode: 44,
    LengthOfInternationalAreaCode: 4,
  },
  {
    capital: 'Hanoi',
    code: 'vn',
    continent: 'Asia',
    iso: true,
    name: 'Vietnam',
    ISOCode: '704',
    InternationalAreaCode: 84,
    LengthOfInternationalAreaCode: 4,
  },

  {
    capital: 'Charlotte Amalie',
    code: 'vi',
    continent: 'North America',
    iso: true,
    name: 'Virgin Islands (U.S.)',
    ISOCode: '850',
    InternationalAreaCode: 1340,
    LengthOfInternationalAreaCode: 6,
  },
  {
    capital: 'Mata-Utu',
    code: 'wf',
    continent: 'Oceania',
    iso: true,
    name: 'Wallis and Futuna',
    ISOCode: '876',
    InternationalAreaCode: 681,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Flying Fish Cove',
    code: 'cx',
    continent: 'Asia',
    iso: true,
    name: 'Christmas Island',
    ISOCode: '162',
    InternationalAreaCode: 61,
    LengthOfInternationalAreaCode: 4,
  },
  {
    capital: 'Bangui',
    code: 'cf',
    continent: 'Africa',
    iso: true,
    name: 'Central African Republic',
    ISOCode: '140',
    InternationalAreaCode: 236,
    LengthOfInternationalAreaCode: 5,
  },
  {
    capital: 'Nicosia',
    code: 'cy',
    continent: 'Europe',
    iso: true,
    name: 'Cyprus',
    ISOCode: '196',
    InternationalAreaCode: 357,
    LengthOfInternationalAreaCode: 5,
  },
];
